name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["Codigo-io/projects/8"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you got!
    validations:
      required: true
  - type: dropdown
    id: extension
    attributes:
      label: Extension
      description: In which blockchain, framework, or programing language does this bug happen?
      multiple: true
      options:
        - Solana Native
        - Solana Anchor
      default: 0
    validations:
      required: true  
  - type: dropdown
    id: target
    attributes:
      label: Target
      description: Where did the bug hapen?
      multiple: true
      options:
        - Smart Contract (Program)
        - Client library (SDK)
      default: 0
    validations:
      required: true  
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our CLI are you running?
      options:
        - 0.1.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Source code
      description: Please copy and paste any relevant code i.e. your CIDL, generated or integration code. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
